
---
- hosts: all
  sudo: true
  vars:
    document_root: /vagrant 
  handlers:
    - name: reload apache
      service: name=apache2
  pre_tasks:
  - name: update apt cache 
    apt: update_cache=yes
  roles:
    - webserver
    - database
